apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-pg-secret
  namespace: utilities
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-store-generated
    kind: ClusterSecretStore
  target:
    name: authentik-pg-secret
    creationPolicy: Owner
  data:
    - secretKey: authentik-postgresql-password
      remoteRef:
        key: authentik-postgresql-password
