apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utilities

resources:
  - cronjob.yaml
  - externalsecret.yaml
  - externalsecret-authentik.yaml

configMapGenerator:
  - name: borgbackup-script
    namespace: utilities
    files:
      - scripts/borg-backup.sh
    options:
      disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: borgbackup
    includeSelectors: true
