services:
  haproxy:
    container_name: haproxy
    image: haproxy:latest@sha256:135f3e6d5a12fb70044e8e1c407b75e1447b1cffa645747da4d38375c3bbbc3e
    user: "0:0"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped
    network_mode: host # Host networking so HAProxy reaches the traefik tailnet IP directly.

  watchtower:
    container_name: watchtower
    image: nickfedor/watchtower:latest@sha256:d76a95a54ab636968f77cb1780fb597b3e28511b535a86e3af212a290ef4d743
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400 # Daily updates
