apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - rbac.yaml
  - policy-configmap.yaml
  - cronjob.yaml

labels:
  - pairs:
      app: descheduler
    includeSelectors: true
