apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    metricsProviders:
      - source: KubernetesMetrics
    profiles:
      - name: LowNodeUtilization
        pluginConfig:
        - name: "DefaultEvictor"
        - name: "LowNodeUtilization"
          args:
            thresholds:
              cpu: 50
              memory: 50
              pods: 50
            targetThresholds:
              cpu: 80
              memory: 80
              pods: 80
            metricsUtilization:
              source: KubernetesMetrics
        plugins:
          balance:
            enabled:
              - "LowNodeUtilization"
