---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: copyparty-secrets
  namespace: utilities
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-store-generated
    kind: ClusterSecretStore
  target:
    name: copyparty-secrets
    creationPolicy: Owner
  data:
    - secretKey: admins
      remoteRef:
        key: copyparty-admins
    - secretKey: writers
      remoteRef:
        key: copyparty-writers
