apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utilities

resources:
  - deployment.yaml
  - service-tailscale.yaml

configMapGenerator:
  - name: copyparty-dav-config
    options:
      disableNameSuffixHash: true
    files:
      - copyparty-dav.conf

labels:
  - pairs:
      app: copyparty-dav
    includeSelectors: true
