apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secrets
  namespace: storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-store
    kind: ClusterSecretStore
  target:
    name: minio-secrets
    creationPolicy: Owner
  data:
    - secretKey: root-user
      remoteRef:
        key: minio-root-user
    - secretKey: root-password
      remoteRef:
        key: minio-root-password
