apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: smtp-credentials
  namespace: utilities
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-store-generated
    kind: ClusterSecretStore
  target:
    name: smtp-credentials
    creationPolicy: Owner
  data:
    - secretKey: host
      remoteRef:
        key: smtp-host
    - secretKey: username
      remoteRef:
        key: smtp-username
    - secretKey: password
      remoteRef:
        key: smtp-password
