apiVersion: apps/v1
kind: Deployment
metadata:
  name: byparr
  namespace: media
  labels:
    app: byparr
spec:
  selector:
    matchLabels:
      app: byparr
  template:
    metadata:
      labels:
        app: byparr
    spec:
      shareProcessNamespace: true
      containers:
        - name: byparr
          image: ghcr.io/thephaseless/byparr:2.1.0@sha256:01a46a2865d9a6db5eb8ead04ec0dd33b8fbe233e8565ae70b50d4cc0af4cfb0
          ports:
            - name: http
              containerPort: 8191
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 1Gi
