apiVersion: apps/v1
kind: Deployment
metadata:
  name: byparr
  namespace: media
  labels:
    app: byparr
spec:
  selector:
    matchLabels:
      app: byparr
  template:
    metadata:
      labels:
        app: byparr
    spec:
      shareProcessNamespace: true
      containers:
        - name: byparr
          image: ghcr.io/thephaseless/byparr:2.1.0
          ports:
            - name: http
              containerPort: 8191
          env:
            - name: PROXY_SERVER
              valueFrom:
                secretKeyRef:
                  name: byparr-proxy
                  key: proxy-server
                  optional: true
            - name: PROXY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: byparr-proxy
                  key: proxy-username
                  optional: true
            - name: PROXY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: byparr-proxy
                  key: proxy-password
                  optional: true
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 1Gi
