apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: byparr-proxy
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-store
    kind: ClusterSecretStore
  target:
    name: byparr-proxy
    creationPolicy: Owner
  data:
    - secretKey: proxy-server
      remoteRef:
        key: byparr-proxy-server
      optional: true
    - secretKey: proxy-username
      remoteRef:
        key: byparr-proxy-username
      optional: true
    - secretKey: proxy-password
      remoteRef:
        key: byparr-proxy-password
      optional: true
