apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-secrets
  namespace: home
spec:
  secretStoreRef:
    name: bitwarden-store-generated
    kind: ClusterSecretStore
  target:
    name: adguard-secrets
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: adguard-admin-password
