apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data-v2
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
