tailscale_args: --ssh --hostname=proxy --accept-dns=false

traefik_backend_host: "traefik.{{ lookup('env', 'TAILSCALE_MAGICDNS_DOMAIN') | default('fold-hen.ts.net', true) }}"
tailscale_authkey: "{{ lookup('env', 'TAILSCALE_ORACLE_AUTH_KEY') }}"
