apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
  labels:
    backup.interstellar/enabled: "true"
  annotations:
    backup.interstellar/excludes: /jellyfin/metadata/library /jellyfin/data/subtitles /jellyfin/metadata/People /jellyfin/metadata/Studio /jellyfin/data/attachments /jellyfin/data/introskipper
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 4Gi
