apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  namespace: media
  labels:
    backup.interstellar/enabled: "true"
  annotations:
    backup.interstellar/excludes: /bazarr/cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
