apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

configMapGenerator:
  - name: prowlarr-custom-definitions
    files:
      - definitions/1337x-byparr.yml
      - definitions/eztv-byparr.yml
    options:
      disableNameSuffixHash: true

labels:
  - pairs:
      app: prowlarr
    includeSelectors: true
