apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: media
  labels:
    backup.interstellar/enabled: "true"
  annotations:
    backup.interstellar/excludes: /prowlarr/logs /prowlarr/logs.db /prowlarr/Backups
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
