apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home

resources:
  - cronjob.yaml
  - externalsecret.yaml

configMapGenerator:
  - name: home-backup-script
    namespace: home
    files:
      - scripts/borg-backup.sh
    options:
      disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/name: home-backup
    includeSelectors: true
