apiVersion: v1
kind: Service
metadata:
  name: byparr-proxy
  namespace: media
spec:
  ports:
    - name: http
      port: 8888
      targetPort: http
  selector:
    app: byparr-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: byparr-proxy-eztv
  namespace: media
spec:
  ports:
    - name: http
      port: 8888
      targetPort: http
  selector:
    app: byparr-proxy-eztv
