apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - common/nfs-storage-config.yaml

  - namespaces.yaml

  - common/

  - jellyfin/
  - seerr/
  - sonarr/
  - radarr/
  - prowlarr/
  - bazarr/
  - qbittorrent/
  - decluttarr/
  - recyclarr/
  - arr-coverage-search/
  - byparr/
  - byparr-proxy/

  - postfix/
  - copyparty/
  - immich/
  - adguard/
  - cloudflare-ddns/

  - networkpolicies/

  - descheduler/

  - borgbackup/
  - media-backup/
  - home-backup/
