apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utilities

resources:
  - externalsecret.yaml
  - deployment.yaml

labels:
  - pairs:
      app: cloudflare-ddns
    includeSelectors: true
