apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
  labels:
    backup.interstellar/enabled: "true"
  annotations:
    backup.interstellar/excludes: /radarr/MediaCover /radarr/Backups /radarr/logs /radarr/logs.db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
