name: Ansible Lint

on:
  push:
    branches: [main, migration]
    paths:
      - "Ansible/**"
      - ".github/workflows/ansible-lint.yaml"
  pull_request:
    branches: [main, migration]
    paths:
      - "Ansible/**"
      - ".github/workflows/ansible-lint.yaml"
  workflow_dispatch:

env:
  ANSIBLE_DIR: "./Ansible"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7

      - name: Install dependencies
        run: uv tool install ansible-core && uv tool install ansible-lint

      - name: Cache Ansible Galaxy content
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ~/.ansible/collections
            ~/.ansible/roles
          key: ${{ runner.os }}-ansible-galaxy-${{ hashFiles('Ansible/requirements.yaml') }}
          restore-keys: |
            ${{ runner.os }}-ansible-galaxy-

      - name: Install Ansible collections
        run: ansible-galaxy install -r requirements.yaml
        working-directory: ${{ env.ANSIBLE_DIR }}

      - name: Run ansible-lint
        run: ansible-lint ${{ env.ANSIBLE_DIR }}
